name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker CLI
        run: |
          echo "${{ secrets.GCP_AR_SA_KEY }}" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
